FROM amazoncorretto:17

MAINTAINER MaraSchneider

COPY . /ArgPrograma

COPY target/ArgPrograma-0.0.1-SNAPSHOT.jar ArgPrograma-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/ArgPrograma-0.0.1-SNAPSHOT.jar"]